"""Phase 1 characterization. Every number in the report traces to this script."""
import collections, re
import numpy as np
import pandas as pd
import data as D

def q(a, p):
    return int(np.percentile(a, p))

raw = D.load_raw()
clean, stats = D.clean(raw)
df = D.load()

out = []
w = out.append

w("## 1. Files in the upstream repo\n")
w("`Reddit_depression_dataset.csv` and `README.md`. Nothing else — no license file,")
w("no annotation guidelines, no per-criterion or per-symptom annotations, no split files.\n")

w("## 2. Raw row/label integrity\n")
w(f"- Rows (excl. header): **{len(raw)}**")
w(f"- Columns: {list(raw.columns)}")
w(f"- Nulls: text={int(raw['text'].isna().sum())}, label={int(raw['label'].isna().sum())}")
w(f"- Empty/whitespace-only texts: {int((raw['text'].fillna('').str.strip()=='').sum())}")
w(f"- Distinct label strings (raw, pre-normalisation): {sorted(raw['label'].astype(str).unique())}")
w("- Label spelling inconsistencies: none. All four values are lowercase and consistent.")
w("  (Note: README and the spec say \"Minimum\"; the CSV uses lowercase `minimum`.)\n")

w("### Duplicates\n")
g = raw.groupby("text")["label"]
dup_groups = g.size()[g.size() > 1]
conf = g.nunique()[g.nunique() > 1]
w(f"- Duplicate text groups: **{len(dup_groups)}** covering {int(dup_groups.sum())} rows "
  f"({int(dup_groups.sum() - len(dup_groups))} redundant).")
w(f"- Of those, groups whose copies carry **different** gold labels: **{len(conf)}**")
for t in conf.index:
    labs = sorted(raw[raw['text'] == t]['label'].tolist())
    w(f"  - `{labs}` — \"{t[:70].replace(chr(10),' ')}...\"")
w("")

w("## 3. Class distribution\n")
w("| Severity | Raw count | Raw % | README count | Clean count | Clean % |")
w("|---|---:|---:|---:|---:|---:|")
readme = {"minimum": 2587, "mild": 290, "moderate": 394, "severe": 282}
rc = raw["label"].value_counts()
cc = clean["label"].value_counts()
for lab in D.LABELS:
    w(f"| {lab} | {rc[lab]} | {rc[lab]/len(raw)*100:.1f}% | {readme[lab]} | "
      f"{cc[lab]} | {cc[lab]/len(clean)*100:.1f}% |")
w(f"| **total** | **{len(raw)}** | | **{sum(readme.values())}** | **{len(clean)}** | |")
w("")
w(f"Raw counts match the upstream README exactly ({'yes' if all(rc[l]==readme[l] for l in D.LABELS) else 'NO'}).")
w(f"Majority-class floor (predict `minimum` always): **accuracy {rc['minimum']/len(raw)*100:.1f}%**, "
  f"macro-F1 {100*(2*1.0*(rc['minimum']/len(raw))/(1+rc['minimum']/len(raw)))/4:.1f}%.\n")

w("## 4. Text length\n")
chars = clean["text"].str.len().values
words = clean["text"].str.split().str.len().values
w("| | p10 | p25 | median | p75 | p90 | p99 | max | mean |")
w("|---|---:|---:|---:|---:|---:|---:|---:|---:|")
for name, a in [("characters", chars), ("whitespace words", words)]:
    w(f"| {name} | {q(a,10)} | {q(a,25)} | {q(a,50)} | {q(a,75)} | {q(a,90)} | "
      f"{q(a,99)} | {a.max()} | {a.mean():.0f} |")
w("")
w(f"Est. prompt tokens per post (words x 1.33): median ~{q(words,50)*1.33:.0f}, p90 ~{q(words,90)*1.33:.0f}.\n")

w("### Length by class\n")
w("| Severity | n | median chars | median words |")
w("|---|---:|---:|---:|")
for lab in D.LABELS:
    s = clean[clean["label"] == lab]["text"]
    w(f"| {lab} | {len(s)} | {int(s.str.len().median())} | {int(s.str.split().str.len().median())} |")
w("")

w("## 5. Cleaning applied\n")
w(f"- Dropped {stats['rows_dropped_conflict']} rows from {stats['conflicting_texts']} "
  "label-conflicting duplicate texts (unresolvable gold label).")
w(f"- Collapsed {stats['rows_dropped_duplicate']} redundant exact-duplicate rows "
  "(prevents train/test leakage).")
w(f"- **{stats['rows_raw']} -> {stats['rows_clean']} rows.**\n")

w("## 6. Split\n")
w("No official split ships with the data. Created a stratified 80/20 split, "
  f"seed `{D.SEED}`, frozen to `data/processed/depseverity_split.csv`.\n")
w("| Severity | train | test | test % of class |")
w("|---|---:|---:|---:|")
for lab in D.LABELS:
    tr = int(((df["split"]=="train") & (df["label"]==lab)).sum())
    te = int(((df["split"]=="test") & (df["label"]==lab)).sum())
    w(f"| {lab} | {tr} | {te} | {te/(tr+te)*100:.1f}% |")
w(f"| **total** | **{int((df['split']=='train').sum())}** | "
  f"**{int((df['split']=='test').sum())}** | |")
w("")
dev = df[df["is_dev"]]
w(f"Prompt-development subset: {len(dev)} posts drawn from train only, class-balanced "
  f"({dict(dev['label'].value_counts())}). Test is untouched.\n")

w("## 7. Per-criterion annotations\n")
w("**None.** The release is `text,label` only. There are no PHQ-9 item labels, no evidence")
w("spans, and no annotator metadata. The C3 extraction step therefore has no gold standard")
w("to be scored against directly — it can only be evaluated end-to-end through aggregation.\n")

report = "\n".join(out)
open("results/phase1_characterization.md", "w").write(
    "# Phase 1 — Data characterization\n\n"
    "Generated by `src/characterize.py`. Do not hand-edit.\n\n" + report)
print(report)
