"""Error analysis the spec calls for: item 9, span grounding, and error direction.

Subreddit breakdown is possible because DepSeverity is relabelled Dreaddit and we
recovered the source community for every post (see notes/findings.md).
"""
import collections
import json

import numpy as np

import aggregate as A
import conditions as C
import data as D
import evaluate as E
import results as R

df = D.load()
sub = df["subreddit"].to_dict()
out = []
w = out.append

w("# Error analysis — test split\n")
w("Generated by `src/error_analysis.py`.\n")

# ---------------------------------------------------------------- item 9
w("## Item 9 (self-harm ideation) vs gold Severe\n")
w("The spec requires this be analysed separately regardless of aggregation rule.\n")
w("| Model | fires on gold-Severe | fires on gold-non-Severe | precision | recall |")
w("|---|---|---|---:|---:|")
for model in R.MODELS:
    recs = [r for r in A.load_run("C3", model, "test") if r.get("items")]
    if len(recs) < 706:
        w(f"| {R.SHORT[model]} | _incomplete ({len(recs)}/706)_ | | | |")
        continue
    fire = np.array([r["items"]["self_harm"]["status"] == "present" for r in recs])
    sev = np.array([r["gold"] == "severe" for r in recs])
    tp, fp = int((fire & sev).sum()), int((fire & ~sev).sum())
    prec = tp / (tp + fp) if tp + fp else float("nan")
    w(f"| {R.SHORT[model]} | {tp}/{int(sev.sum())} | {fp}/{int((~sev).sum())} | "
      f"{prec:.3f} | {tp/int(sev.sum()):.3f} |")
w("")

# ------------------------------------------------------- span grounding
w("## Span grounding — are quoted evidence spans real?\n")
w("Every `present` item returns a verbatim span. An ungrounded span is a hallucination;")
w("this is measurable at zero extra cost and we are not aware of it being reported")
w("elsewhere in this literature.\n")
w("| Model | spans checked | found verbatim in post | rate |")
w("|---|---:|---:|---:|")
for model in R.MODELS:
    recs = [r for r in A.load_run("C3", model, "test") if r.get("grounding") is not None]
    if len(recs) < 700:
        w(f"| {R.SHORT[model]} | _incomplete_ | | |")
        continue
    vals = [v for r in recs for v in r["grounding"].values() if v is not None]
    w(f"| {R.SHORT[model]} | {len(vals)} | {sum(vals)} | {sum(vals)/len(vals):.3f} |")
w("")

# ------------------------------------------------- errors by subreddit
w("## Error direction by source community\n")
w("DepSeverity drops the subreddit; we recovered it by matching to Dreaddit. There is")
w("no depression subreddit in the corpus, which is the mechanism behind the sparse")
w("extraction.\n")
for model in R.MODELS:
    got = R.label_preds("C2", model)
    try:
        agg = A.build(model)
    except SystemExit:
        continue
    if not got or len(got[0]) < 700:
        continue
    w(f"### {R.SHORT[model]}\n")
    w("| subreddit | n | C2 MAE | C3 MAE | C2 under | C3 under |")
    w("|---|---:|---:|---:|---:|---:|")
    recs = [r for r in A.load_run("C2", model, "test") if r.get("pred")]
    c2 = {r["id"]: (C.LABELS.index(r["gold"]), C.LABELS.index(r["pred"])) for r in recs}
    c3 = {i: (yt, yp) for i, yt, yp in zip(agg["ids"], agg["y_true"], agg["y_pred"])}
    by = collections.defaultdict(list)
    for i in c3:
        if i in c2:
            by[sub.get(i, "?")].append(i)
    for s, ids in sorted(by.items(), key=lambda kv: -len(kv[1])):
        a = np.array([c2[i] for i in ids]); b = np.array([c3[i] for i in ids])
        w(f"| {s} | {len(ids)} | {np.abs(a[:,0]-a[:,1]).mean():.3f} | "
          f"{np.abs(b[:,0]-b[:,1]).mean():.3f} | "
          f"{(a[:,1]<a[:,0]).mean():.3f} | {(b[:,1]<b[:,0]).mean():.3f} |")
    w("")

txt = "\n".join(out)
open("results/error_analysis.md", "w").write(txt)
print(txt)
